### ISSUE TITLE
Unable to make gradient from 270° to 90° passing through 0°

### ISSUE THREAD

**Issue by webstrand** [saneef/color-color#23]
For instance this gradient passes through 180°:
![image](https://github.com/saneef/color-color/assets/373938/cd70298e-c46c-42e5-adaa-85dc66b32260)

It should instead look like this (made by changing `store.js#config.limit.hue=[0,720]`):
![image](https://github.com/saneef/color-color/assets/373938/a7c4e969-5c85-4fa0-b5d0-0591ae4a6caa)

I can't figure out how otherwise to make a blue -> purple -> red gradient.

**Comment by saneef** [comment]
Thank you, @webstrand, for reporting this bug. 

This should be working now.

**Comment by saneef** [comment]
Hey @webstrand. I had to revert the fix. 

The tool is meant for generating shades and tints of a colour. I needed the control to shift hue in a close range _forwards as well as backwards_. You can read about the trick [in this article](https://medium.com/@erikdkennedy/color-in-ui-design-a-practical-framework-e18cacd97f9e#:~:text=The%20trick%20is%20to%20just%20make%20the%20movement%20of%20the%20hue%20match%20up%20with%20the%20movement%20of%20the%20saturation%20and%20brightness.).

**Comment by webstrand** [comment]
@saneef If I understand correctly your fix automatically selected the direction, either backwards or forwards based on the absolute distance in degrees between the two points. This causes issues because you can't pick which "direction" around the circle the gradient should go. Do I have that all correct?

I agree, automatically picking the direction, cw/ccw, isn't ideal either. I suggest three alternatives:

1. Extend the range of the `start`/`end` sliders to be [0, 720], this way any two points on the hue circle can be picked and the gradient always goes from `start` to `end`.
2. Add a checkbox "Reverse Gradient" or "via 360". (Note that the arc via 360 may be shorter, so don't use a name indicating distance)
3. Make the ending hue relative to the start instead of an absolute position. For instance `start: 270` and `end: +90`. This may be advantageous for simulating the behavior of real shadows, too.

Finally, I wonder if the shift in the hue of shadows is related to white-balance in the real world.

**Comment by saneef** [comment]
Yes, I understand the problem. I compute the hue over the shortest distance. It worked with the use cases I had in my mind. :D 

I would like to know more about your use case? Would you mind telling me a bit more about what you're trying to achieve? Are you trying to get a set of colours (range of hues) with a similar luminance or chroma? 

If I find such a case useful for others, I can work out something. One way forward I see is having a checkbox (like point 2 you mentioned).

**Comment by webstrand** [comment]
@saneef That was just me making sure I understood the problem correctly, not trying to explain it to you, to be clear.

An effect like this is basically what I was trying to achieve:
![image](https://github.com/saneef/color-color/assets/373938/e6af57af-7faa-4392-9fad-fab316f1aef4)

None of the gradients I want go that far into red. But stopping at 360 isn't far enough.

**Comment by saneef** [comment]
Okay. Let me figure a way to add this.

**Comment by saneef** [comment]
I brought back the interpolation direction. It can be enabled using a checkbox.

<img width="1314" alt="SCR-20240207-ozpd" src="https://github.com/saneef/color-color/assets/81863/f6d92936-ccd9-486d-a52d-af97874b8eb0">
