### ISSUE TITLE
Add option to duplicate current color

### ISSUE THREAD

**Issue by jceb** [saneef/color-color#25]
Currently, there's a button to add more colors. It seems like it adds predefined colors. I'd appreciate a button that would duplicate my existing color settings so I can base my next color on my previous settings.

**Comment by saneef** [comment]
Thanks, @jceb, for the suggestions. 

I made a release with a button to clone a palette. For me, duplicating a colour (the hue) and filling in the rest of the parameters (saturation,...) is similar to clone.
